### ISSUE TITLE
timeout: invalid time interval 'ffmpeg'

### ISSUE THREAD

**Issue by wfchan** [zkhan93/cctv#2]
timeout: invalid time interval 'ffmpeg'
Try 'timeout --help' for more information.

**Comment by zkhan93** [comment]
can you give some more information on which container is failing with this error and some logs around it. also it would help if you can attach your compose file

**Comment by btalanski** [comment]
@wfchan  solved the issue by setting the following env vars in docker-compose file for the `recorder` services:

- DURATION=600
- FORMAT=mp4
- SEGMENT_FORMAT=%Y-%m-%d_%H-%M-%S

@zkhan93 would be really nice you listed the env vars that needs to be set on the `.env` file or `docker-compose` services declaration.

**Comment by zkhan93** [comment]
thanks @btalanski for pointing that out, I will add and example.env

**Comment by btalanski** [comment]
I'm still struggling to get the `merger` application to perform properly. It might be something related to a improper env value in my settings. That example `.env` file will definitely help a lot!

Thank you very much for sharing this tool here on github.

**Comment by zkhan93** [comment]
here's my .env file
```text
############### DOCKER COMPOSE ############
OUT=/mnt/data/cctv

################### COMMON #############
TZ=Asia/Kolkata

################### RECORDER #################
FORMAT=mkv
DURATION=600
SEGMENT_FORMAT=%d-%m-%Y_%H%M%S

##################### MERGE #########################
CLEANUP_SPACE=45
CLEANUP_REGEX=.*-[0-9]+_\(cam[0-9]\|mosaic\).*
CLEANUP_DIR=/out/

############################ DELETE THIS LATER #####################
TIMEOUT_BUFFER=10
```

this is what I have on my server, there might be something that needs to be removed.
CLEANUP_SPACE is in GBs

**Comment by btalanski** [comment]
@zkhan93 thanks for sharing that!
